import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'docs-site-index',
    'getting-started',
    'concepts',
    'skills',
    'architecture',
    'api-reference',
    {
      type: 'category',
      label: 'User Guide',
      link: {
        type: 'doc',
        id: 'user-guide/README',
      },
      items: [{ type: 'autogenerated', dirName: 'user-guide' }],
    },
    {
      type: 'category',
      label: 'Developer Guide',
      link: {
        type: 'doc',
        id: 'developer-guide/README',
      },
      items: [{ type: 'autogenerated', dirName: 'developer-guide' }],
    },
    {
      type: 'category',
      label: 'Engineering Blog',
      link: {
        type: 'doc',
        id: 'blog/README',
      },
      items: [{ type: 'autogenerated', dirName: 'blog' }],
    },
  ],
};

export default sidebars;
